### ISSUE TITLE
The main.py file for the BiLSTM model is missing

### ISSUE THREAD

**Issue by nilavghosh** [hiaoxui/Chinese-Word-Segmentation-with-BiLSTM-CRF#1]
Hi Author, 

Could you please share the main.py file, which initiates the model, trains and then evaluates the model. Would be really grateful if you could do that. 

Thanks,
NIlav Ghosh

**Comment by nilavghosh** [comment]
Hey.. i have been able to write one myself. Thank you,

**Comment by mokeam** [comment]
Hi, do you mind sharing the one you’ve written please?
